binary_sensor:
  - platform: template
    id: id_template_api_status
    internal: True
    condition:
      api.connected:
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_ha_status
            text_color: color_blue
    on_release: 
      then:
        - lvgl.label.update: 
            id: id_lv_lab_ha_status
            text_color: color_dark_gray

  # Front door from HA #
  - platform: homeassistant
    id: id_ha_side_door
    entity_id: binary_sensor.ademcointerposer_porte_de_cote
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_side_door
            hidden: false
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_side_door
            hidden: true

  # Patio door from HA #
  - platform: homeassistant
    id: id_ha_patio_door
    entity_id: binary_sensor.ademcointerposer_patio
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_patio_door
            hidden: false
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_patio_door
            hidden: true

  # Miner is running from HA #
  - platform: homeassistant
    id: id_ha_mining_running
    entity_id: binary_sensor.mining_rig_est_en_fonction
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_miner_status
            text_color: color_orange
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_miner_status
            text_color: color_dark_gray

  # Hibiscus needs water from HA #
  - platform: homeassistant
    id: id_ha_hibiscus_watering
    entity_id: binary_sensor.hibiscus_a_soif
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_hibiscus_watering
            hidden: false
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_hibiscus_watering
            hidden: true

  # Lys de paix needs water from HA #
  - platform: homeassistant
    id: id_ha_lysdepaix_watering
    entity_id: binary_sensor.lys_de_paix_a_soif
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_lysdepaix_watering
            hidden: false
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_lysdepaix_watering
            hidden: true

  # Défi Hilo Status from HA #
  - platform: homeassistant
    id: id_ha_defi_hilo_active
    entity_id: binary_sensor.defi_hilo_thermostat_central_override_is_active
    publish_initial_state: True
    on_press:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_defi_hilo
            hidden: false
    on_release:
      then:
        - lvgl.label.update: 
            id: id_lv_lab_defi_hilo
            hidden: true

interval:
  - interval: 800ms
    startup_delay: 0s
    then:
      - if:
          condition: 
            - lambda: "return id(id_blinker_toggle) == false;"
          then:
            - lvgl.label.update: 
                id: id_lv_lab_defi_hilo
                text_color: color_yellow
            - globals.set:
                id: id_blinker_toggle
                value: "true"
          else:
            - lvgl.label.update: 
                id: id_lv_lab_defi_hilo
                text_color: color_dark_gray
            - globals.set:
                id: id_blinker_toggle
                value: "false"