script:
  - id: id_script_blink_lock_ico
    mode: restart
    then:
      - lvgl.button.update: 
          id: id_lv_but_lock_side
          shadow_opa: TRANSP
      - repeat:
          count: 45  # 45 x 1000ms = 45 seconds
          then:
            - lvgl.widget.hide: id_lv_lab_ico_lock_side
            - delay: 500ms
            - lvgl.widget.show: id_lv_lab_ico_lock_side
            - delay: 500ms
      - lvgl.widget.show: id_lv_lab_ico_lock_side
      - lvgl.button.update: 
          id: id_lv_but_lock_side
          shadow_opa: COVER

  - id: id_script_blink_garage_ico
    mode: restart
    then:
      - lvgl.button.update: 
          id: id_lv_but_garage_door
          shadow_opa: TRANSP
      - repeat:
          count: 20  # 20 x 1000ms = 20 seconds
          then:
            - lvgl.widget.hide: id_lv_lab_ico_garage_door
            - delay: 500ms
            - lvgl.widget.show: id_lv_lab_ico_garage_door
            - delay: 500ms
      - lvgl.widget.show: id_lv_lab_ico_garage_door
      - lvgl.button.update: 
          id: id_lv_but_garage_door
          shadow_opa: COVER


binary_sensor:
  - platform: homeassistant
    id: id_bin_lock_side
    internal: true
    entity_id: binary_sensor.etat_verrou_porte_de_cote
    publish_initial_state: true
    on_press:
      then:
        - script.stop: id_script_blink_lock_ico
        - lvgl.button.update: 
            id: id_lv_but_lock_side
            shadow_color: color_red
        - lvgl.label.update:
            id: id_lv_lab_lock_side
            text_color: color_red
        - lvgl.label.update:
            id: id_lv_lab_ico_lock_side
            text_color: color_red
            text: "${unlocked}"
            hidden: false
        - lvgl.button.update: 
            id: id_lv_but_lock_side
            shadow_opa: COVER
    on_release:
      then:
        - script.stop: id_script_blink_lock_ico
        - lvgl.button.update: 
            id: id_lv_but_lock_side
            shadow_color: color_green
        - lvgl.label.update:
            id: id_lv_lab_lock_side
            text_color: color_green
        - lvgl.label.update:
            id: id_lv_lab_ico_lock_side
            text_color: color_green
            text: "${locked}"
            hidden: false
        - lvgl.button.update: 
            id: id_lv_but_lock_side
            shadow_opa: COVER

  - platform: homeassistant
    id: id_bin_garage_door
    internal: true
    entity_id: binary_sensor.garage_door_opener_tat_de_la_porte
    publish_initial_state: true
    on_press:
      then:
        - lvgl.button.update: 
            id: id_lv_but_garage_door
            shadow_color: color_red
        - lvgl.label.update:
            id: id_lv_lab_garage_door
            text_color: color_red
        - lvgl.label.update:
            id: id_lv_lab_ico_garage_door
            text_color: color_red
            text: "${garage_door_open}"
            hidden: false
        - lvgl.button.update: 
            id: id_lv_but_garage_door
            shadow_opa: COVER
    on_release:
      then:
        - script.stop: id_script_blink_garage_ico
        - lvgl.button.update: 
            id: id_lv_but_garage_door
            shadow_color: color_green
        - lvgl.label.update:
            id: id_lv_lab_garage_door
            text_color: color_green
        - lvgl.label.update:
            id: id_lv_lab_ico_garage_door
            text_color: color_green
            text: "${garage_door_closed}"
            hidden: false
        - lvgl.button.update: 
            id: id_lv_but_garage_door
            shadow_opa: COVER

